### ISSUE TITLE
Failed to process config callback url

### ISSUE THREAD

**Issue by adambarber** [bear-metal/tunemygc#10]
I'm running this on Heroku. 

When viewing the logs, I see a lot of 
```[TuneMyGC, pid: 365] Failed to process config callback url https://tunemygc.com/configs/XXX.json (error: hostname "tunemygc.com" does not match the server certificate)``` and the suggested configuration never gets logged.

**Comment by erkki** [comment]
Thanks for reporting, we've gotten other similar reports and are looking into this, if you could run this in the context of the app (say a separate +x file with heroku run) it'd help alot:

https://gist.github.com/erkki/420a22c323b6efff5c7b

Thanks!

**Comment by methodmissing** [comment]
@adambarber fixed in 1.0.35 and earlier - the agent now yields a report URL with the configuration and a lot more insights
