### ISSUE TITLE
No log output for rspec

### ISSUE THREAD

**Issue by somebody32** [bear-metal/tunemygc#17]
Hi,

there is no log output at all when I'm trying to run tunemygc + rspec, except initial message about railtie:
`[TuneMyGC] Rails detected, loading railtie`

So there is no way to understand if measurement succeeded or not

**Comment by methodmissing** [comment]
@somebody32 mind adding "RUBY_GC_SPY=rspec" to your environment and reporting back if it worked for you? ( https://github.com/bear-metal/tunemygc#advanced )

**Comment by somebody32** [comment]
@methodmissing I started with that initially, no difference at all

**Comment by methodmissing** [comment]
@somebody32 synced with you via email

**Comment by Fryguy** [comment]
I am having the same problem trying to profile our rspec tests.  Also, not sure this matters, but we have multiple test suites, so I'm not sure what this is going to do when the same token is used across the suites.  See https://travis-ci.org/Fryguy/manageiq/builds/67890184 for the test suites (note that vmdb is really the one I care about).

**Comment by Fryguy** [comment]
Oh I just noticed some other issues around VCR.  We do have some VCR specs.  What changes do I have to make to support this, though?
