### ISSUE TITLE
Add note about VCR integration

### ISSUE THREAD

**Issue by somebody32** [bear-metal/tunemygc#18]
It will be good to note somewhere in the Readme about adding `tunemygc.com` to the VCR whitelist, or otherwise it just dies silently without sending any data. (or maybe it will be not the case when #17 is fixed)

**Comment by somebody32** [comment]
Looks like a duplicate of #8, so feel free to close

**Comment by methodmissing** [comment]
@somebody32 Ack, we need to special case Webmock or VCR somehow, or preferably note in the README for steps for such frameworks as it's in the application specific domain
