### ISSUE TITLE
Ruby 2.2.2 and Rails 4.2.1

### ISSUE THREAD

**Issue by aubreyrhodes** [bear-metal/tunemygc#21]
I got the following after trying to profile an app on the latest versions of ruby an rails:

```
Ruby version 2.2.2 or Rails version 4.2.1 not supported. Failed to sync 465 snapshots
```

Any news on when these will be supported?

**Comment by methodmissing** [comment]
@aubreyrhodes setting Ruby 2.2.2 as a Travis CI target and pushing a change to our service. Allow a few mins. Thanks for flagging!

**Comment by aubreyrhodes** [comment]
Awesome, thanks for the quick response!

**Comment by aubreyrhodes** [comment]
Just tried and it synced correctly. Thanks again!

**Comment by methodmissing** [comment]
Interested in Beta testing an Heroku addon with this?

**Comment by aubreyrhodes** [comment]
@methodmissing Sure!

**Comment by methodmissing** [comment]
Email addy linked to your Heroku app / account to tunemygc@bearmetal.eu . Thanks!
