### ISSUE TITLE
Registration error: #<Timeout::Error: execution expired>

### ISSUE THREAD

**Issue by JoshMcKin** [bear-metal/tunemygc#25]
I would like to make use of this tool but when I attempt to register I get the following error:

```
JMcKinney:hq jmckinney$ bundle exec tunemygc -r someEmail@text.com
[tunemygc] not enabled
Registration error: #<Timeout::Error: execution expired>
```

**Comment by methodmissing** [comment]
Hi Josh,

Mind retrying? It looks like an intermittent network error ...

**Comment by JoshMcKin** [comment]
No problem.

Unfortunately got the same error.

**Comment by JoshMcKin** [comment]
Tried just now and got the same error.

If it helps I'm using ruby 2.2.2 and rails 3.2.22

**Comment by methodmissing** [comment]
Hi Josh,

Tried a few more times and asked folks in different places too. Mind trying the following and seeing if it times out too ? (curl is independent from any other stack diffs):

```bash
curl -d 'email=test%40domain.com%26app=test' -X POST https://tunemygc.com/accounts
```

**Comment by JoshMcKin** [comment]
Returned `40c09675d7be70296ad1f88bc10161a6`

But took a couple minutes.
