### ISSUE TITLE
Can not `bundle install` with tunemygc v1.0.61

### ISSUE THREAD

**Issue by danielricecodes** [bear-metal/tunemygc#29]
Hello,

I'm seeing the following in my console when I try to install the tunemygc gem.  Is there a dependency I'm missing?  I'm using MRI 2.2.2, Rails 4.2.5, RVM, Bundler, and OSX Yosemite 10.10.5.  I've also installed Development Tools - I have compiled several C extensions for other gems without issue.

Thank you in advance!

```bash
An error occurred while installing tunemygc (1.0.61), and Bundler cannot continue.
Make sure that `gem install tunemygc -v '1.0.61'` succeeds before bundling.
Daniel-Rices-MacBook-Pro:chrome_capital danielrice$ gem install tunemygc -v '1.0.61'
Building native extensions.  This could take a while...
ERROR:  Error installing tunemygc:
	ERROR: Failed to build gem native extension.

    /Users/danielrice/.rvm/rubies/ruby-2.2.2/bin/ruby -r ./siteconf20151117-94349-1ditci6.rb extconf.rb
checking for RUBY_INTERNAL_EVENT_GC_END_SWEEP... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/danielrice/.rvm/rubies/ruby-2.2.2/bin/$(RUBY_BASE_NAME)
	--with-tunemygc-dir
	--without-tunemygc-dir
	--with-tunemygc-include
	--without-tunemygc-include=${tunemygc-dir}/include
	--with-tunemygc-lib
	--without-tunemygc-lib=${tunemygc-dir}/lib
/Users/danielrice/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /Users/danielrice/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/mkmf.rb:571:in `block in try_compile'
	from /Users/danielrice/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/mkmf.rb:524:in `with_werror'
	from /Users/danielrice/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/mkmf.rb:571:in `try_compile'
	from /Users/danielrice/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/mkmf.rb:1225:in `try_const'
	from /Users/danielrice/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/mkmf.rb:1256:in `block in have_const'
	from /Users/danielrice/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/mkmf.rb:911:in `block in checking_for'
	from /Users/danielrice/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/mkmf.rb:351:in `block (2 levels) in postpone'
	from /Users/danielrice/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/mkmf.rb:321:in `open'
	from /Users/danielrice/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/mkmf.rb:351:in `block in postpone'
	from /Users/danielrice/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/mkmf.rb:321:in `open'
	from /Users/danielrice/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/mkmf.rb:347:in `postpone'
	from /Users/danielrice/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/mkmf.rb:910:in `checking_for'
	from /Users/danielrice/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/mkmf.rb:1255:in `have_const'
	from extconf.rb:8:in `<main>'
```

**Comment by danielricecodes** [comment]
Tried that already.  I have developer tools installed.  There aren't any
dependencies other than Xcode Developer Tools (which are installed) ?

On Tue, Nov 17, 2015 at 4:41 PM, Tarmo Tänav <notifications@github.com>
wrote:

> The error message says "You have to install development tools first" which
> means the compiler is not quite working. "xcode-select --install" might
> help with this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bear-metal/tunemygc/issues/29#issuecomment-157517696>.
>



-- 

[image: --]
Daniel Rice
Co-Founder & CTO
LD Studios, LLC
+1 404 376 4434
http://www.ldstudios.co
Meet with me <https://calendly.com/daniel-rice>
skype: phonk64
github: danielricecodes

**Comment by tarmo** [comment]
Have you tried running the compiler separately to test that it can generate executables? So for example make a test.c file containing "int main() { return 0; }" and run "gcc test.c"

**Comment by danielricecodes** [comment]
@tarmo - thanks for the information.  I was able to fix the issue by running `gcc`.  Oddly enough, this is what the first suggestion does:

```bash
danielrice$ xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
```

Seems normal.  There have been some updates to Xcode lately with Swift and El Capitan's release.  I did these updates already though and the usual `xcode-select --install` did not bring up the license agreement like it has in the past.

However, when I tried to compile the sample C file you suggested, `gcc` brought up the license agreement prompt I was used to seeing with `xcode-select`.  Odd.

Either way, this is fixed now.  Turned out I had to compile *anything* with gcc, re-agree to Apple's TOS, and voilà.  

```bash
danielrice$ bundle
Fetching gem metadata from http://rubygems.org/..........
Fetching version metadata from http://rubygems.org/...
Fetching dependency metadata from http://rubygems.org/..
Resolving dependencies.......
....
Installing tunemygc 1.0.61 with native extensions
....
Bundle complete! 95 Gemfile dependencies, 247 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

:bow:
