### ISSUE TITLE
Doesn't detect config loaded via dotenv

### ISSUE THREAD

**Issue by mintuhouse** [bear-metal/tunemygc#37]
I set my config (secret keys & other env variables) via [dotenv](https://github.com/bkeepers/dotenv). When I set RUBY_GC_TUNE via dotenv, it is not being detected and I get 
`[tunemygc] not enabled`
And no data is being sent

**Comment by tarmo** [comment]
Hey @mintuhouse, this is very likely a problem with how you've set up dotenv and not having any experience with dotenv I don't know what the problem might be. Using spring could be causing ENV changes not to get picked up automatically, but that's just one of many possibilities

From the tunemygc gem perspective it shouldn't matter what or how is setting ENV variables as long as they are set when the application loads the gem, for me direnv (which seems to be similar to dotenv) works fine with tunemygc.
