### ISSUE TITLE
RUBY_GC_TUNE_VERBOSE=0 does not silence "[tunemygc] Rails detected, loading railtie" message

### ISSUE THREAD

**Issue by atd** [bear-metal/tunemygc#45]
Shouldn't it be the expected behavior? Would you accept a PR?

**Comment by methodmissing** [comment]
Yes please :-) #patcheswelcome

**Comment by atd** [comment]
@methodmissing could you please cut a new gem version? :pray:

**Comment by methodmissing** [comment]
@atd :tada: https://rubygems.org/gems/tunemygc/versions/1.0.71
