### ISSUE TITLE
log writing failed. can't be called from trap context

### ISSUE THREAD

**Issue by schneems** [bear-metal/tunemygc#5]
I'm trying to run this with https://github.com/schneems/derailed_benchmarks to generate load on my app. I just get this phrase over and over again:

```
log writing failed. can't be called from trap context
log writing failed. can't be called from trap context
log writing failed. can't be called from trap context
log writing failed. can't be called from trap context
log writing failed. can't be called from trap context
log writing failed. can't be called from trap context
log writing failed. can't be called from trap context
log writing failed. can't be called from trap context
log writing failed. can't be called from trap context
log writing failed. can't be called from trap context
log writing failed. can't be called from trap context
log writing failed. can't be called from trap context
log writing failed. can't be called from trap context
log writing failed. can't be called from trap context
```

Any ideas?

**Comment by methodmissing** [comment]
Hi @schneems ,

That's fairly common with stdlib default Logger and Threads. I noticed you're running the server you're benchmarking in a Thread @ https://github.com/schneems/derailed_benchmarks/blob/master/lib/derailed_benchmarks/tasks.rb#L67

There's a crude work around option in https://github.com/steveklabnik/mono_logger

I noticed this once before, but didn't want to add another dependency for the default logger: https://github.com/bear-metal/tunemygc/blob/master/lib/tunemygc/agent.rb#L57

Are you running derailed with the context of a Rails or Rack app?

**Comment by schneems** [comment]
I wasn't using that flag, this is the code that was being hit: https://github.com/schneems/derailed_benchmarks/blob/master/lib/derailed_benchmarks/tasks.rb#L87-L96

Running `rake -f perf.rake perf:test TEST_COUNT=5000 RUBY_GC_TUNE=1` doesn't use any threads

Without setting `USE_SERVER` flag this is the `call_app` function that gets hit https://github.com/schneems/derailed_benchmarks/blob/master/lib/derailed_benchmarks/tasks.rb#L79-L83

**Comment by methodmissing** [comment]
Ack. Pushed version 1.0.24 which tries to use MonoLogger (https://github.com/steveklabnik/mono_logger) and stdlib Logger as fallback:  https://github.com/bear-metal/tunemygc/commit/a8dbf1267943b6ef6f50e115f87a2ca3cceafb25

As a means to unblock you, mind adding mono_logger to your Gemfile and bump tunemygc to 1.0.24?

**Comment by schneems** [comment]
I updated to 1.0.32 and it works even without monologger. Thanks!
