### ISSUE TITLE
RSpec cannot be loaded

### ISSUE THREAD

**Issue by pacoguzman** [bear-metal/tunemygc#6]
I'm using this for my test suite but I'm getting the following error

```sh
require 'rspec' -- cannot load such file
```

I've changed the code to

```ruby
require 'rspec/core'
```

And everything works. I'm using rspec-rails 2.14. I can test if 'rspec/core' works for newer versions too

**Comment by methodmissing** [comment]
Thanks for flagging, pushing a fix too

**Comment by methodmissing** [comment]
Whoops, *soon*

**Comment by methodmissing** [comment]
Handled in https://github.com/bear-metal/tunemygc/commit/29ac8fe0a72654513370683034e4f4bab4462bd7 and release 1.0.27 . Mind verifying and closing if fixed?

**Comment by pacoguzman** [comment]
It's working fine now thanks!
