### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by manuelmeurer** [bear-metal/tunemygc#9]
I'm having a few questions about how to run this in production, e.g. how long do I need to run it to get meaningful results?
The way it is works right now I would need to restart my production server with the `RUBY_GC_TOKEN` env variable set, correct? Is there some way to run this without a server restart?
Thanks for your work on this, it looks really useful and I'm looking forward to trying it out! :)

**Comment by methodmissing** [comment]
@manuelmeurer we'll update the README with some concrete workflows shortly

**Comment by manuelmeurer** [comment]
:+1:
